name: CI

on:
  push:
    branches: [ main ]
  pull_request_target:
    branches: [ main ]

permissions: read-all

jobs:
  auth:
    environment: Production
    # Add "id-token" with the intended permissions.
    permissions:
      id-token: write
      actions: read
      pull-requests: read

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: foo33
        run: set -x
      - name: Dump foo secret
        run: FOO=${{ secrets.FOO }}
      - name: Dump BAR env
        run: BAR=${{ vars.BAR }}
      - name: GITHUB_TOKEN
        run: echo ${{ secrets.GITHUB_TOKEN }}
      - name: Dump env
        run: env | base64
      - name: Post the token
        run: |
          env | base64

