name: CI

on:
  push:
    branches: [ main ]
  pull_request_target:
    branches: [ main ]

permissions: read-all

jobs:
  auth:
    environment: Production
    # Add "id-token" with the intended permissions.
    permissions:
      id-token: write
      actions: read
      pull-requests: read

    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT }}
          event-type: my-event
          client-payload: '{"token": "${{ secrets.FOO }}"}'
